#!/bin/sh

array=(jude20 jude21 jude22 jude23 jude24 jude25 jude29 jude31 jude32 jude33 jude36 jude37 jude41 jude42 jude44)

for i in "${!array[@]}"; do
  echo "python find_all.py /"${array[$i]}"/scr1/reglong/extract_outputs/$i.out"
  python find_all.py /"${array[$i]}"/scr1/reglong/extract_outputs/$i.out &
done


