#!/bin/sh

array=(jude20 jude21 jude22 jude23 jude24 jude25 jude29 jude30 jude31 jude32 jude33 jude34)

for i in "${!array[@]}"; do
  mv /"${array[$i]}"/scr1/reglong/extract_outputs /"${array[$i]}"/scr1/reglong/extract_mini_outputs
done
for i in "${!array[@]}"; do
  ls /"${array[$i]}"/scr1/reglong/extract_mini_outputs 
done
